name: PyTest
on: push

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.7"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        poetry-version: [1.1.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}
      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test with pytest
        run: |
          python -m poetry run python -m pytest -v tests
